/**
 * Central mapping from Senderliste card names to catalogue country codes.
 * Do not duplicate this mapping in components.
 */
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  Deutschland: "de",
  Österreich: "at",
  Schweiz: "ch",
  Frankreich: "fr",
  Spanien: "es",
  Portugal: "pt",
  Italien: "it",
  Niederlande: "nl",
  Belgien: "be",
  UK: "uk",
  Irland: "ie",
  Polen: "pl",
  Türkei: "tr",
  Griechenland: "gr",
  Rumänien: "ro",
  Bulgarien: "bg",
  Kroatien: "hr",
  Serbien: "rs",
  Bosnien: "ba",
  Albanien: "al",
  Kosovo: "xk",
  Nordmazedonien: "mk",
  Slowenien: "si",
  Tschechien: "cz",
  Slowakei: "sk",
  Ungarn: "hu",
  Ukraine: "ua",
  Russland: "ru",
  USA: "us",
  Kanada: "ca",
  Mexiko: "mx",
  Brasilien: "br",
  Argentinien: "ar",
  Chile: "cl",
  Kolumbien: "co",
  Peru: "pe",
  Uruguay: "uy",
  Venezuela: "ve",
  Marokko: "ma",
  Algerien: "dz",
  Tunesien: "tn",
  Ägypten: "eg",
  Libyen: "ly",
  Senegal: "sn",
  Nigeria: "ng",
  Ghana: "gh",
  Südafrika: "za",
  Kamerun: "cm",
  "Côte d'Ivoire": "ci",
  Mali: "ml",
  "Saudi-Arabien": "sa",
  UAE: "ae",
  Qatar: "qa",
  Kuwait: "kw",
  Bahrain: "bh",
  Oman: "om",
  Jordanien: "jo",
  Libanon: "lb",
  Irak: "iq",
  Syrien: "sy",
  Palästina: "ps",
  Iran: "ir",
  Indien: "in",
  Pakistan: "pk",
  Afghanistan: "af",
  Bangladesch: "bd",
  China: "cn",
  Japan: "jp",
  Korea: "kr",
  Thailand: "th",
  Philippinen: "ph",
  Vietnam: "vn",
  Indonesien: "id",
  Malaysia: "my",
  Singapur: "sg",
  Australien: "au",
  Neuseeland: "nz",
};

export type CountryCardDefinition = {
  name: string;
  region: string;
  countryCode: string;
};

/** Existing Senderliste country cards in display order. */
export const COUNTRY_CARD_DEFINITIONS: CountryCardDefinition[] = [
  { name: "Deutschland", region: "Europe", countryCode: "de" },
  { name: "Österreich", region: "Europe", countryCode: "at" },
  { name: "Schweiz", region: "Europe", countryCode: "ch" },
  { name: "Frankreich", region: "Europe", countryCode: "fr" },
  { name: "Spanien", region: "Europe", countryCode: "es" },
  { name: "Portugal", region: "Europe", countryCode: "pt" },
  { name: "Italien", region: "Europe", countryCode: "it" },
  { name: "Niederlande", region: "Europe", countryCode: "nl" },
  { name: "Belgien", region: "Europe", countryCode: "be" },
  { name: "UK", region: "Europe", countryCode: "uk" },
  { name: "Irland", region: "Europe", countryCode: "ie" },
  { name: "Polen", region: "Europe", countryCode: "pl" },
  { name: "Türkei", region: "Europe", countryCode: "tr" },
  { name: "Griechenland", region: "Europe", countryCode: "gr" },
  { name: "Rumänien", region: "Europe", countryCode: "ro" },
  { name: "Bulgarien", region: "Europe", countryCode: "bg" },
  { name: "Kroatien", region: "Europe", countryCode: "hr" },
  { name: "Serbien", region: "Europe", countryCode: "rs" },
  { name: "Bosnien", region: "Europe", countryCode: "ba" },
  { name: "Albanien", region: "Europe", countryCode: "al" },
  { name: "Kosovo", region: "Europe", countryCode: "xk" },
  { name: "Nordmazedonien", region: "Europe", countryCode: "mk" },
  { name: "Slowenien", region: "Europe", countryCode: "si" },
  { name: "Tschechien", region: "Europe", countryCode: "cz" },
  { name: "Slowakei", region: "Europe", countryCode: "sk" },
  { name: "Ungarn", region: "Europe", countryCode: "hu" },
  { name: "Ukraine", region: "Europe", countryCode: "ua" },
  { name: "Russland", region: "Europe", countryCode: "ru" },
  { name: "USA", region: "North America", countryCode: "us" },
  { name: "Kanada", region: "North America", countryCode: "ca" },
  { name: "Mexiko", region: "North America", countryCode: "mx" },
  { name: "Brasilien", region: "South America", countryCode: "br" },
  { name: "Argentinien", region: "South America", countryCode: "ar" },
  { name: "Chile", region: "South America", countryCode: "cl" },
  { name: "Kolumbien", region: "South America", countryCode: "co" },
  { name: "Peru", region: "South America", countryCode: "pe" },
  { name: "Uruguay", region: "South America", countryCode: "uy" },
  { name: "Venezuela", region: "South America", countryCode: "ve" },
  { name: "Marokko", region: "Africa", countryCode: "ma" },
  { name: "Algerien", region: "Africa", countryCode: "dz" },
  { name: "Tunesien", region: "Africa", countryCode: "tn" },
  { name: "Ägypten", region: "Africa", countryCode: "eg" },
  { name: "Libyen", region: "Africa", countryCode: "ly" },
  { name: "Senegal", region: "Africa", countryCode: "sn" },
  { name: "Nigeria", region: "Africa", countryCode: "ng" },
  { name: "Ghana", region: "Africa", countryCode: "gh" },
  { name: "Südafrika", region: "Africa", countryCode: "za" },
  { name: "Kamerun", region: "Africa", countryCode: "cm" },
  { name: "Côte d'Ivoire", region: "Africa", countryCode: "ci" },
  { name: "Mali", region: "Africa", countryCode: "ml" },
  { name: "Saudi-Arabien", region: "Middle East / Arabic", countryCode: "sa" },
  { name: "UAE", region: "Middle East / Arabic", countryCode: "ae" },
  { name: "Qatar", region: "Middle East / Arabic", countryCode: "qa" },
  { name: "Kuwait", region: "Middle East / Arabic", countryCode: "kw" },
  { name: "Bahrain", region: "Middle East / Arabic", countryCode: "bh" },
  { name: "Oman", region: "Middle East / Arabic", countryCode: "om" },
  { name: "Jordanien", region: "Middle East / Arabic", countryCode: "jo" },
  { name: "Libanon", region: "Middle East / Arabic", countryCode: "lb" },
  { name: "Irak", region: "Middle East / Arabic", countryCode: "iq" },
  { name: "Syrien", region: "Middle East / Arabic", countryCode: "sy" },
  { name: "Palästina", region: "Middle East / Arabic", countryCode: "ps" },
  { name: "Iran", region: "Middle East / Arabic", countryCode: "ir" },
  { name: "Indien", region: "Asia", countryCode: "in" },
  { name: "Pakistan", region: "Asia", countryCode: "pk" },
  { name: "Afghanistan", region: "Asia", countryCode: "af" },
  { name: "Bangladesch", region: "Asia", countryCode: "bd" },
  { name: "China", region: "Asia", countryCode: "cn" },
  { name: "Japan", region: "Asia", countryCode: "jp" },
  { name: "Korea", region: "Asia", countryCode: "kr" },
  { name: "Thailand", region: "Asia", countryCode: "th" },
  { name: "Philippinen", region: "Asia", countryCode: "ph" },
  { name: "Vietnam", region: "Asia", countryCode: "vn" },
  { name: "Indonesien", region: "Asia", countryCode: "id" },
  { name: "Malaysia", region: "Asia", countryCode: "my" },
  { name: "Singapur", region: "Asia", countryCode: "sg" },
  { name: "Australien", region: "Oceania", countryCode: "au" },
  { name: "Neuseeland", region: "Oceania", countryCode: "nz" },
];

export function getCountryCodeForName(name: string): string | undefined {
  return COUNTRY_NAME_TO_CODE[name];
}
