import type { TopicCategory } from "@/lib/senderliste/types";

/** Non-country Senderliste categories preserved from the existing page. */
export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    id: "skandinavien",
    name: "Skandinavien",
    region: "Europe",
    channels: [
      { name: "SVT1 HD", category: "Allgemein" },
      { name: "SVT2 HD", category: "Allgemein" },
      { name: "TV4 Sweden HD", category: "Allgemein" },
      { name: "NRK1 HD", category: "Allgemein" },
      { name: "NRK2 HD", category: "Allgemein" },
      { name: "TV2 Norway HD", category: "Allgemein" },
      { name: "DR1 HD", category: "Allgemein" },
      { name: "TV2 Denmark HD", category: "Allgemein" },
      { name: "Yle TV1 HD", category: "Allgemein" },
    ],
  },
  {
    id: "arabische-sender",
    name: "Arabische Sender",
    region: "Middle East / Arabic",
    channels: [
      { name: "Al Jazeera HD", category: "Nachrichten" },
      { name: "Al Arabiya HD", category: "Nachrichten" },
      { name: "Sky News Arabia HD", category: "Nachrichten" },
      { name: "Al Mayadeen HD", category: "Nachrichten" },
      { name: "Rotana Cinema", category: "Filme" },
      { name: "Rotana Drama", category: "Serien" },
    ],
  },
  {
    id: "mbc",
    name: "MBC",
    region: "Middle East / Arabic",
    channels: [
      { name: "MBC 1 HD", category: "Allgemein" },
      { name: "MBC 2 HD", category: "Filme" },
      { name: "MBC 3 HD", category: "Kinder" },
      { name: "MBC 4 HD", category: "Allgemein" },
      { name: "MBC Action HD", category: "Filme" },
      { name: "MBC Drama HD", category: "Serien" },
      { name: "MBC Bollywood HD", category: "Filme" },
      { name: "Shahid VIP Kategorien", category: "Unterhaltung" },
    ],
  },
  {
    id: "osn",
    name: "OSN",
    region: "Middle East / Arabic",
    channels: [
      { name: "OSN Movies HD", category: "Filme" },
      { name: "OSN Series HD", category: "Serien" },
      { name: "OSN Kids HD", category: "Kinder" },
      { name: "OSN Yahala HD", category: "Unterhaltung" },
      { name: "OSN Sports HD", category: "Sport" },
    ],
  },
  {
    id: "bein-arab",
    name: "beIN Arab",
    region: "Middle East / Arabic",
    channels: [
      { name: "beIN Sports 1 HD", category: "Sport" },
      { name: "beIN Sports 2 HD", category: "Sport" },
      { name: "beIN Sports 3 HD", category: "Sport" },
      { name: "beIN Sports 4 HD", category: "Sport" },
      { name: "beIN Movies HD", category: "Filme" },
      { name: "beIN Series HD", category: "Serien" },
    ],
  },
  {
    id: "sport",
    name: "Sport",
    region: "Sport Categories",
    channels: [
      { name: "Sky Sport HD", category: "Sport" },
      { name: "DAZN HD", category: "Sport" },
      { name: "Eurosport HD", category: "Sport" },
      { name: "beIN Sports HD", category: "Sport" },
      { name: "ESPN HD", category: "Sport" },
      { name: "Fox Sports HD", category: "Sport" },
      { name: "Sportdigital HD", category: "Sport" },
    ],
  },
  {
    id: "fussball",
    name: "Fußball",
    region: "Sport Categories",
    channels: [
      { name: "Bundesliga HD", category: "Sport" },
      { name: "Champions League HD", category: "Sport" },
      { name: "Europa League HD", category: "Sport" },
      { name: "Premier League HD", category: "Sport" },
      { name: "La Liga HD", category: "Sport" },
      { name: "Serie A HD", category: "Sport" },
      { name: "Ligue 1 HD", category: "Sport" },
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    region: "Sport Categories",
    channels: [
      { name: "Sky Bundesliga 1 HD", category: "Sport" },
      { name: "Sky Bundesliga 2 HD", category: "Sport" },
      { name: "Sky Bundesliga 3 HD", category: "Sport" },
      { name: "DAZN Bundesliga HD", category: "Sport" },
      { name: "Sport1 Bundesliga", category: "Sport" },
    ],
  },
  {
    id: "champions-league",
    name: "Champions League",
    region: "Sport Categories",
    channels: [
      { name: "DAZN Champions League HD", category: "Sport" },
      { name: "Prime Video Sport HD", category: "Sport" },
      { name: "beIN Champions HD", category: "Sport" },
      { name: "Sky Sport Austria HD", category: "Sport" },
    ],
  },
  {
    id: "premier-league",
    name: "Premier League",
    region: "Sport Categories",
    channels: [
      { name: "Sky Sports Premier League HD", category: "Sport" },
      { name: "TNT Sports HD", category: "Sport" },
      { name: "USA Network Sports", category: "Sport" },
      { name: "NBC Sports HD", category: "Sport" },
    ],
  },
  {
    id: "la-liga",
    name: "La Liga",
    region: "Sport Categories",
    channels: [
      { name: "Movistar LaLiga HD", category: "Sport" },
      { name: "DAZN LaLiga HD", category: "Sport" },
      { name: "LaLiga TV Bar HD", category: "Sport" },
    ],
  },
  {
    id: "serie-a",
    name: "Serie A",
    region: "Sport Categories",
    channels: [
      { name: "DAZN Serie A HD", category: "Sport" },
      { name: "Sky Calcio HD", category: "Sport" },
      { name: "Sport Italia HD", category: "Sport" },
    ],
  },
  {
    id: "ligue-1",
    name: "Ligue 1",
    region: "Sport Categories",
    channels: [
      { name: "Canal+ Foot HD", category: "Sport" },
      { name: "beIN Ligue 1 HD", category: "Sport" },
      { name: "Prime Video Ligue 1", category: "Sport" },
    ],
  },
  {
    id: "motorsport",
    name: "Motorsport",
    region: "Sport Categories",
    channels: [
      { name: "Formula 1 HD", category: "Sport" },
      { name: "Sky F1 HD", category: "Sport" },
      { name: "Motorsport TV HD", category: "Sport" },
      { name: "MotoGP HD", category: "Sport" },
      { name: "NASCAR HD", category: "Sport" },
    ],
  },
  {
    id: "ufc-und-boxen",
    name: "UFC & Boxen",
    region: "Sport Categories",
    channels: [
      { name: "UFC Fight Pass HD", category: "Sport" },
      { name: "DAZN Fight Night HD", category: "Sport" },
      { name: "Boxing TV HD", category: "Sport" },
      { name: "Fight Sports HD", category: "Sport" },
    ],
  },
  {
    id: "nba",
    name: "NBA",
    region: "Sport Categories",
    channels: [
      { name: "NBA TV HD", category: "Sport" },
      { name: "ESPN NBA HD", category: "Sport" },
      { name: "TNT Sports NBA HD", category: "Sport" },
      { name: "Sky Sports NBA HD", category: "Sport" },
    ],
  },
  {
    id: "nfl",
    name: "NFL",
    region: "Sport Categories",
    channels: [
      { name: "NFL Network HD", category: "Sport" },
      { name: "ESPN NFL HD", category: "Sport" },
      { name: "Fox NFL HD", category: "Sport" },
      { name: "CBS Sports HD", category: "Sport" },
    ],
  },
  {
    id: "tennis",
    name: "Tennis",
    region: "Sport Categories",
    channels: [
      { name: "Tennis Channel HD", category: "Sport" },
      { name: "Eurosport Tennis HD", category: "Sport" },
      { name: "Sky Tennis HD", category: "Sport" },
      { name: "beIN Tennis HD", category: "Sport" },
    ],
  },
  {
    id: "filme",
    name: "Filme",
    region: "Entertainment",
    channels: [
      { name: "Sky Cinema HD", category: "Filme" },
      { name: "Warner TV Film HD", category: "Filme" },
      { name: "Paramount Movies HD", category: "Filme" },
      { name: "AMC HD", category: "Filme" },
      { name: "FilmBox HD", category: "Filme" },
      { name: "Canal+ Cinema HD", category: "Filme" },
    ],
  },
  {
    id: "serien",
    name: "Serien",
    region: "Entertainment",
    channels: [
      { name: "Warner TV Serie HD", category: "Serien" },
      { name: "AXN HD", category: "Serien" },
      { name: "Syfy HD", category: "Serien" },
      { name: "13th Street HD", category: "Serien" },
      { name: "Universal TV HD", category: "Serien" },
      { name: "Fox Series HD", category: "Serien" },
    ],
  },
  {
    id: "netflix-kategorien",
    name: "Netflix Kategorien",
    region: "Entertainment",
    channels: [
      { name: "Netflix Action", category: "Filme" },
      { name: "Netflix Drama", category: "Serien" },
      { name: "Netflix Serien", category: "Serien" },
      { name: "Netflix Kids", category: "Kinder" },
      { name: "Netflix Dokumentation", category: "Dokumentation" },
      { name: "Netflix Comedy", category: "Unterhaltung" },
    ],
  },
  {
    id: "prime-video-kategorien",
    name: "Prime Video Kategorien",
    region: "Entertainment",
    channels: [
      { name: "Prime Video Action", category: "Filme" },
      { name: "Prime Video Serien", category: "Serien" },
      { name: "Prime Video Sport", category: "Sport" },
      { name: "Prime Video Filme", category: "Filme" },
      { name: "Prime Video Kids", category: "Kinder" },
    ],
  },
  {
    id: "disney-kategorien",
    name: "Disney+ Kategorien",
    region: "Entertainment",
    channels: [
      { name: "Disney+ Filme", category: "Filme" },
      { name: "Disney+ Serien", category: "Serien" },
      { name: "Disney+ Kids", category: "Kinder" },
      { name: "Marvel", category: "Filme" },
      { name: "Star Wars", category: "Filme" },
      { name: "National Geographic Disney+", category: "Dokumentation" },
    ],
  },
  {
    id: "hbo-kategorien",
    name: "HBO Kategorien",
    region: "Entertainment",
    channels: [
      { name: "HBO Movies", category: "Filme" },
      { name: "HBO Series", category: "Serien" },
      { name: "HBO Max Originals", category: "Serien" },
      { name: "HBO Drama", category: "Serien" },
      { name: "HBO Comedy", category: "Unterhaltung" },
    ],
  },
  {
    id: "dokumentation",
    name: "Dokumentation",
    region: "Entertainment",
    channels: [
      { name: "National Geographic HD", category: "Dokumentation" },
      { name: "Discovery HD", category: "Dokumentation" },
      { name: "History HD", category: "Dokumentation" },
      { name: "Animal Planet HD", category: "Dokumentation" },
      { name: "Travel Channel HD", category: "Reisen" },
      { name: "Arte Doku HD", category: "Dokumentation" },
    ],
  },
  {
    id: "nachrichten",
    name: "Nachrichten",
    region: "Entertainment",
    channels: [
      { name: "CNN HD", category: "Nachrichten" },
      { name: "BBC News HD", category: "Nachrichten" },
      { name: "Euronews HD", category: "Nachrichten" },
      { name: "Al Jazeera HD", category: "Nachrichten" },
      { name: "Sky News HD", category: "Nachrichten" },
      { name: "Welt HD", category: "Nachrichten" },
      { name: "NTV HD", category: "Nachrichten" },
    ],
  },
  {
    id: "kinder",
    name: "Kinder",
    region: "Entertainment",
    channels: [
      { name: "Super RTL HD", category: "Kinder" },
      { name: "KiKA HD", category: "Kinder" },
      { name: "Nickelodeon HD", category: "Kinder" },
      { name: "Cartoon Network HD", category: "Kinder" },
      { name: "Disney Channel HD", category: "Kinder" },
      { name: "Boomerang HD", category: "Kinder" },
    ],
  },
  {
    id: "musik",
    name: "Musik",
    region: "Entertainment",
    channels: [
      { name: "MTV HD", category: "Musik" },
      { name: "Deluxe Music HD", category: "Musik" },
      { name: "Trace Urban HD", category: "Musik" },
      { name: "NRJ Hits HD", category: "Musik" },
      { name: "Clubbing TV HD", category: "Musik" },
      { name: "VH1 HD", category: "Musik" },
    ],
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    region: "Entertainment",
    channels: [
      { name: "TLC HD", category: "Lifestyle" },
      { name: "HGTV HD", category: "Lifestyle" },
      { name: "Food Network HD", category: "Lifestyle" },
      { name: "Fashion TV HD", category: "Lifestyle" },
      { name: "Travel XP HD", category: "Reisen" },
    ],
  },
  {
    id: "religion",
    name: "Religion",
    region: "Entertainment",
    channels: [
      { name: "Quran TV HD", category: "Religion" },
      { name: "Sunnah TV HD", category: "Religion" },
      { name: "Bibel TV HD", category: "Religion" },
      { name: "Religious TV HD", category: "Religion" },
      { name: "Peace TV HD", category: "Religion" },
    ],
  },
];
